project = 'Selene DRMCairo plug-in'
title = 'Selene DRM/Cairo graphical plug-in'
dir = 'docs/DRMCairo'
description = "Selene's DRM/Cairo plug-in"
full_description = [[
DRMCairo is a lightweight framework to create decent graphics without the
need to install X.

[Back to top level documentation](../)
]]
use_markdown_titles = true
format = "markdown"

add_language_extension("sel", "lua")
examples = "./SelenitesDRMCairo"
