
project = 'Selene library'
title = 'Selene library documentation'
file = './src/SeleneLibrary'
dir = 'docs/Selene'
description = "Selene's own library"
full_description = [[
Selene's library provides several **objects** to ease messaging, event handling and data storing.

[Back to top level documentation](../)
]]
use_markdown_titles = true
format = "markdown"

add_language_extension("sel", "lua")
examples = "./Selenites"
