
project = 'Selene Curses plug-in'
title = 'Selene text based plug-in'
dir = 'docs/Curses'
description = "Selene's Curses plug-in"
full_description = [[
This plug-in provides an easy way to implement a text based graphics to Séléné / Lua application.

[Back to top level documentation](../)
]]
use_markdown_titles = true
format = "markdown"

add_language_extension("sel", "lua")
examples = "./SelenitesCurses"
